name: Build XIVLauncher AutoOTP
on: [push]

jobs:
  build:
    name: Build Release on Windows
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-2022
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: Initialize Submodules
        run: git submodule update --init --recursive
      - 
        name: Restore Nuget Packages
        run: |
          cd .\src\
          dotnet restore
          cd ..
      - 
        name: Define VERSION
        run: |
          $env:COMMIT = $env:GITHUB_SHA.Substring(0, 7)
          $env:REPO_NAME = $env:GITHUB_REPOSITORY -replace '.*/'
          $env:BRANCH = $env:GITHUB_REF -replace '.*/'
          ($env:REPO_NAME) >> VERSION
          ($env:BRANCH) >> VERSION
          ($env:COMMIT) >> VERSION
      - 
        name: Build DotNet4 for Release
        run: |
          cd "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\src\XIVLauncherAutoOTP.sln /t:Build /p:Configuration=Release
          cd $Env:GITHUB_WORKSPACE\src\
          dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false
      - 
        name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            src\Releases\**
            src\XIVLauncherAutoOTP\bin\Release\net6.0\win-x64\publish\**
          name: Release
      - 
        name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: xivlauncherautootp-artifact
          path: src\XIVLauncherAutoOTP\bin\Release\net6.0\
      -
        name: VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: ./src\XIVLauncherAutoOTP\bin\Release\net6.0\win-x64\publish\*.exe